# rpc节点的ip地址
rpcserverip=127.0.0.1
# rpc节点的端口号
rpcserverport=8000
# zk的ip地址
zookeeperip=127.0.0.1
# zk的prot端口号
zookeeperport=2181
# zk连接超时时间（毫秒）
zookeeperconnecttimeout=5000
# zk会话超时时间（毫秒）
zookeepersessiontimeout=30000
# rpc连接超时时间（毫秒）
rpcconnecttimeout=3000
# rpc发送超时时间（毫秒）
rpcsendtimeout=3000
# rpc接收超时时间（毫秒）
rpcrecvtimeout=5000
