# local userservice config
RPC_BIND_IP=127.0.0.1
RPC_PORT=9000
RPC_ADVERTISE_HOST=127.0.0.1
RPC_IO_THREADS=4
ZK_ENDPOINTS=127.0.0.1:2181
MPRPC_ZK_NAMESPACE=mprpc
ZK_CONNECT_TIMEOUT_MS=5000
ZK_SESSION_TIMEOUT_MS=30000
RPC_CONNECT_TIMEOUT_MS=3000
RPC_SEND_TIMEOUT_MS=3000
RPC_RECV_TIMEOUT_MS=5000
MPRPC_LOG_MODE=stdout
MPRPC_LOG_DIR=logs
